### ISSUE TITLE
好像没有效果

### ISSUE THREAD

**Issue by GitDjAr** [llm-sys/Thinking-Claude-Pipeline#1]
我不知道错过了什么操作,我按照函数导入似乎没有效果
![image](https://github.com/user-attachments/assets/bf90e8f8-a032-4a1d-ac34-83d9c173a691)

**Comment by fangtaosong** [comment]
Thanks for the suggestion, since I'm writing in the pipeline style, not the filter method, the pipes() method will overwrite the old model, so you may need to register the new model in the workplace, and then I'll consider rewriting it with fiter.

感谢你提供的建议，因为我是按照pipeline的写法，而不是filter的写法写的，pipes()方法会覆盖原有的模型，所以可能需要在workplace里注册成新模型，之后我会考虑用fiter重写它


![image](https://github.com/user-attachments/assets/c6650887-5ff0-4f2f-8b56-c000a21b0a40)
